### ISSUE TITLE
You use my package with license CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by baligh-p** [everything-registry/everything#16]
You use my package with license CC BY-NC-ND 4.0

**Comment by eklem** [comment]
They are just a bunch of shitheads and they won't follow licenses either.

**Comment by PatrickJS** [comment]
https://github.com/everything-registry/everything/assets/1016365/107e69de-7a72-471a-af5d-e9f31b2c494a

**Comment by PatrickJS** [comment]
the code we use is all MIT we do not use any package. anyone using this package will be using your code but only if they can even install it which is impossible unless you have 1tb of RAM

**Comment by eklem** [comment]
https://www.npmjs.com/package/everything

**Comment by baligh-p** [comment]
I want delete my package from npm and i can't because your project depend
on mine.

Le mar. 2 janv. 2024 à 6:53 AM, Espen Klem ***@***.***> a
écrit :

**Comment by PatrickJS** [comment]
please contact npm about unpublishing you package. I'm also trying to get in contact with anyone there to update their unpublish policy. this was an edge-case that they didn't think of after they created the policy (which was created years later after this package was initially created/published 10 years ago)

**Comment by baligh-p** [comment]
sorry for that.
can you help me by removing my package from your package if you can ofc.

Le mar. 2 janv. 2024 à 9:23 PM, PatrickJS ***@***.***> a
écrit :
