### ISSUE TITLE
Deleting a package.

### ISSUE THREAD

**Issue by titsex** [everything-registry/everything#19]
Hi. I want to delete my package, but I can't because it is a dependency of yours. Can you remove it from the dependencies? https://www.npmjs.com/package/distube-vk-music-plugin

**Comment by PatrickJS** [comment]
I'm trying to get in contact with anyone at npm. this is an issue with their unpublish policy that was created after this package was initial created and published

**Comment by PatrickJS** [comment]
please refer to https://github.com/everything-registry/everything/issues/17
